main:
  - {name: 首页, url: /, weight: 10}
  - {name: 研究方向, url: /research/, weight: 20}
  - {name: 团队, url: /team/, weight: 30}
  - {name: 科研成果, url: /outputs/, weight: 40}
  - {name: 实验平台, url: /facilities/, weight: 60}
  - {name: 新闻, url: /news/, weight: 70}
  - {name: 加入我们, url: /join-us/, weight: 80}
