main:
  - {name: Home, url: /en/, weight: 10}
  - {name: Research, url: /en/research/, weight: 20}
  - {name: Team, url: /en/team/, weight: 30}
  - {name: Outputs, url: /en/outputs/, weight: 40}
  - {name: Facilities, url: /en/facilities/, weight: 60}
  - {name: News, url: /en/news/, weight: 70}
  - {name: Join Us, url: /en/join-us/, weight: 80}
